spring:
  data:
    mongodb:
      host: 10.10.5.51
      port: 27017
      uri: mongodb://10.10.5.51/test
#      field-naming-strategy: org.springframework.boot.autoconfigure.data.mongo
  redis:
    host: 10.10.5.51
    port: 6379